"""github auth parent task webhook log

Revision ID: b44c5b38a400
Revises: c6322425f9a7
Create Date: 2026-09-01 10:00:31.293357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b44c5b38a400'
down_revision: Union[str, Sequence[str], None] = 'c6322425f9a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('task_ref', sa.String(length=40), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('members', sa.Column('github_id', sa.String(length=40), nullable=True))
    op.add_column('members', sa.Column('github_login', sa.String(length=80), nullable=True))
    op.add_column('members', sa.Column('avatar_url', sa.Text(), nullable=True))
    op.add_column('members', sa.Column('email', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'members', ['github_id'])
    op.add_column('tasks', sa.Column('parent_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'parent_id')
    op.drop_constraint(None, 'members', type_='unique')
    op.drop_column('members', 'email')
    op.drop_column('members', 'avatar_url')
    op.drop_column('members', 'github_login')
    op.drop_column('members', 'github_id')
    op.drop_table('webhook_events')
    # ### end Alembic commands ###
