"""task ai fields

Revision ID: c6322425f9a7
Revises: 6ac13eb64e2e
Create Date: 2026-08-31 15:23:42.962386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6322425f9a7'
down_revision: Union[str, Sequence[str], None] = '6ac13eb64e2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('estimate_hours', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('complexity', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('complexity')
        batch_op.drop_column('estimate_hours')
        batch_op.drop_column('tags')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
