"""project github repo

Revision ID: f3253475ad9d
Revises: f7fb0b937768
Create Date: 2026-09-01 15:14:51.187203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3253475ad9d'
down_revision: Union[str, Sequence[str], None] = 'f7fb0b937768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('github_repo', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'github_repo')
    # ### end Alembic commands ###
